mex -v -o ambient_occlusion -DMEX -largeArrayDims ...
  -I/opt/local/include/eigen3 -I/usr/local/igl/libigl/include ...
  -L/usr/local/igl/libigl/lib -ligl -liglmatlab -liglembree ...
  CXXFLAGS="\$CXXFLAGS -m64 -msse4.2 -fopenmp" ...
  -I/usr/local/igl/libigl/external/embree/rtcore ...
  -I/usr/local/igl/libigl/external/embree/common ...
  -L/usr/local/igl/libigl/external/embree/bin -lrtcore -lsys ... 
  mexFunction.cpp parse_rhs.cpp;

